[package]
name = "append-only-store"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = "0.12.1"
rand = "0.8.5"
dashmap = "5.5.3"
blake3 = "1.5.1"
